const mockDisclaimer =
  "This output was generated by an AI assistant and does not constitute a final legal decision. All outputs must be reviewed and approved by Legal Affairs.";

export function buildMockLegalReviewResult(filename) {
  return {
    request_category: "Vendor Agreement",
    category_confidence: 0.86,
    extracted_clauses: [
      {
        clause_title: "Scope of Services",
        clause_text:
          "Vendor will provide cloud-based analytics services as described in Exhibit A.",
        location_hint: "Section 1",
      },
      {
        clause_title: "Payment Terms",
        clause_text:
          "University agrees to pay $54,000 annually, net 30 days from invoice.",
        location_hint: "Section 3",
      },
      {
        clause_title: "Auto-Renewal",
        clause_text:
          "Agreement renews automatically unless cancelled 90 days before term end.",
        location_hint: "Section 2",
      },
      {
        clause_title: "Limitation of Liability",
        clause_text:
          "Vendor liability capped at total fees paid in preceding 12 months.",
        location_hint: "Section 6",
      },
    ],
    missing_or_unusual_clauses: [
      {
        clause_title: "Data Security / FERPA Compliance",
        issue_type: "missing",
        explanation:
          "No data protection or FERPA language found despite vendor handling student data.",
      },
      {
        clause_title: "Insurance Requirements",
        issue_type: "missing",
        explanation:
          "Standard template requires vendor to carry specified insurance coverage.",
      },
      {
        clause_title: "Governing Law",
        issue_type: "unusual",
        explanation:
          "Agreement specifies Delaware law rather than the university home state.",
      },
    ],
    template_comparisons: [
      {
        template_name: "Vendor Services Agreement Template v2.1",
        match_score: 0.65,
        deviations: [
          "Missing FERPA Compliance clause",
          "Missing Insurance Requirements",
          "Governing law is Delaware, not university home state",
          "Liability cap below standard minimum",
        ],
      },
    ],
    risk_highlights: [
      {
        term: "Limitation of Liability",
        risk_level: "high",
        reason:
          "Cap of $54,000 is insufficient to cover damages from a student data breach.",
        clause_text:
          "Vendor liability shall not exceed fees paid in the preceding 12 months.",
      },
      {
        term: "Auto-Renewal (90-day notice)",
        risk_level: "medium",
        reason:
          "90-day cancellation window is longer than the university standard of 30 days.",
      },
      {
        term: "One-sided Indemnification",
        risk_level: "medium",
        reason:
          "University bears broad indemnification; vendor obligations to university are narrow.",
      },
    ],
    obligations_summary: [
      "Pay $54,000 annually within 30 days of invoice.",
      "Provide system access needed for vendor to deliver services.",
      "Ensure users comply with vendor acceptable use policy.",
      "Bear broad indemnification obligations toward the vendor.",
      "Cannot terminate during the initial 12-month term for convenience.",
    ],
    draft_review_note:
      `DRAFT REVIEW NOTE — ${filename}\n\n` +
      "This Vendor Services Agreement has been reviewed against the university standard template. Several issues require attention before signature:\n\n" +
      "1. No FERPA / data security clause despite vendor handling student data.\n" +
      "2. Liability cap is below university standard minimum.\n" +
      "3. Auto-renewal notice period exceeds university standard.\n" +
      "4. Indemnification clause is significantly one-sided.\n" +
      "5. Governing law may create jurisdictional complications.\n\n" +
      "This is a first-draft note for Legal Affairs review. It does not constitute final approval.",
    suggested_questions: [
      "Can the vendor add a FERPA-compliant data processing addendum?",
      "Can the liability cap be increased to the university standard minimum?",
      "Can the auto-renewal notice period be reduced from 90 to 30 days?",
      "Is the vendor willing to include a mutual indemnification clause?",
      "Can governing law be changed to the university home state?",
    ],
    related_precedents: [
      {
        title: "Vendor Agreement with CloudSoft Inc. (2023)",
        document_type: "Vendor Agreement",
        summary:
          "SaaS vendor agreement; required FERPA data processing addendum and breach notification clause.",
        similarity_score: 0.87,
        source_id: "PRECEDENT-0027",
      },
    ],
    disclaimer: mockDisclaimer,
    ai_mode: "mock",
  };
}

function readFileAsBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = () => {
      const dataUrl = String(reader.result || "");
      const base64 = dataUrl.includes(",") ? dataUrl.split(",")[1] : dataUrl;
      resolve(base64);
    };

    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(file);
  });
}

export async function analyzeLegalDocument(file) {
  const shouldUseMock = import.meta.env.VITE_USE_MOCK_AI_REVIEW === "true";
  const functionsUrl = import.meta.env.VITE_SUPABASE_FUNCTIONS_URL;
  const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

  // BEGINNER DOCUMENTATION:
  // Mock mode is only used when explicitly enabled. If mock mode is disabled,
  // the PDF must go to the Supabase Edge Function, which calls Gemini securely.
  if (shouldUseMock) {
    await new Promise((resolve) => setTimeout(resolve, 700));
    return buildMockLegalReviewResult(file.name);
  }

  if (!functionsUrl) {
    throw new Error(
      "Supabase Functions URL is missing. Set VITE_SUPABASE_FUNCTIONS_URL to call Gemini review.",
    );
  }

  const fileBase64 = await readFileAsBase64(file);
  const response = await fetch(`${functionsUrl}/legal-review`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(anonKey ? { Authorization: `Bearer ${anonKey}` } : {}),
    },
    body: JSON.stringify({
      fileName: file.name,
      mimeType: file.type || "application/pdf",
      fileBase64,
    }),
  });

  const result = await response.json();

  if (!response.ok) {
    throw new Error(result.error || "AI legal review failed.");
  }

  return result;
}

/*
BEGINNER DOCUMENTATION:

1. Why is the Gemini API not called directly from React?
React code runs in the browser. If we put the Gemini API key here, users could inspect the browser bundle and steal it.

2. What does this file do?
It sends the uploaded document to a Supabase Edge Function. The Edge Function is backend code, so it can safely use secret keys.

3. Why keep mock mode?
Mock mode lets the frontend demo work even before Supabase secrets are configured.
*/
